name: Greetings

on: [pull_request, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: 'Thanks for joining the ranks of many valuable contributors to awesome-single-cell!'
        pr-message: 'Thanks for joining the ranks of many valuable contributors to awesome-single-cell!'
